version: '3.9'

# Development docker-compose configuration
# Use: docker-compose -f docker-compose.dev.yml up

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: icoach-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-icoach_db}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - icoach-dev-network

  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: icoach-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-icoach_nosql}
    ports:
      - "${MONGO_PORT:-27018}:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - icoach-dev-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: icoach-redis-dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - icoach-dev-network

networks:
  icoach-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local
